use `*database_name`
To fix observed error in C driver tests:

```
error: database backpressure-db not found
```

The `*database_name` is used in initialData, creating the database before the test.